[tools]
rojo = "rojo-rbx/rojo@7.7.1"
wally = "upliftgames/wally@0.3.2"
selene = "kampfkarren/selene@0.32.0"
stylua = "johnnymorganz/stylua@2.5.2"
lune = "lune-org/lune@0.10.5"
luau-lsp = "johnnymorganz/luau-lsp@1.70.1"
