--!strict
return {
	WELCOME = {
		night = 1,
	},
	ACT_II = {
		night = 4,
	},
	ACT_III = {
		night = 7,
	},
	ACT_IV = {
		night = 10,
	},
	SURVIVOR = {
		night = 12,
	},
	PAID_IN_FULL = {
		ending = "PAID_IN_FULL",
	},
	RINGMASTERS = {
		ending = "RINGMASTERS",
	},
	PART_OF_THE_ACT = {
		ending = "PART_OF_THE_ACT",
	},
	HARD_HAT = {
		difficulty = "Hard",
	},
	BILL_BUSTER = {
		tickets = 250000,
	},
	ENDLESS_15 = {
		night = 15,
	},
	ENDLESS_20 = {
		night = 20,
	},
	ENDLESS_25 = {
		night = 25,
	},
	HUMAN_CANNONBALL = {
		launches = 1,
	},
	POCKET_CHANGE = {
		tickets = 10000,
	},
	BIG_POCKETS = {
		tickets = 1000000,
	},
	TICKET_TYCOON = {
		tickets = 100000000,
	},
	TICKET_TITAN = {
		tickets = 10000000000,
	},
	CARNIVAL_LEGEND = {
		tickets = 100000000000,
	},
	BULLSEYE_WHEEL = {
		floor = 4,
	},
	PERFECT_21 = {
		floor = 4,
		total = 21,
	},
	ROYAL_QUACK = {
		floor = 3,
		waddles = 3,
	},
	DUCK_ROYALTY = {
		floor = 4,
	},
	HOME_RUN = {
		floor = 4,
	},
	TEN_OUT_OF_TEN = {
		floor = 3,
		multiplier = 10,
	},
	GOLD_SPLAT = {
		floor = 4,
	},
	COLD_FEET = {
		lane = 10,
	},
	PHOTOGRAPHIC_MEMORY = {
		hits = 5,
	},
	TO_THE_MOON = {
		multiplier = 25,
	},
	NEEDLE_MASTER = {
		multiplier = 25,
	},
	EDGE_MASTER = {
		floor = 4,
		multiplier = 24,
	},
	TOP_OF_FUNHOUSE = {
		row = 8,
	},
	PIE_PROOF = {
		pies = 8,
	},
	FOUR_OF_A_KIND = {
		matches = 4,
	},
	GUTTER_GENIUS = {
		openingPins = 0,
	},
	JUGGLE_LEGEND = {
		catches = 50,
	},
	FULL_CREW = {
		crew = 6,
	},
	BEST_FRIENDS = {
		nights = 10,
	},
	MVP = {
		awards = 1,
	},
	PROFESSIONAL_LOSER = {
		awards = 5,
	},
	NOTHING_LEFT_TO_PAWN = {
		pieces = 3,
	},
	DUCK_HUNTER = {
		finds = 10,
	},
	GADGET_COLLECTOR = {
		items = 16,
	},
	SHUTTERBUG = {
		photos = 10,
	},
	BATTER_UP = {
		bonks = 1,
	},
}
